//! systems domain.

pub mod advisor_system;
pub mod assignment_system;
pub mod incident_system;
pub mod job_decision_system;
pub mod mission_system;
pub mod mood_system;
pub mod objective_system;
pub mod planning_system;
#[cfg(not(target_arch = "wasm32"))]
pub mod playtest_report;
#[cfg(not(target_arch = "wasm32"))]
pub mod playtest_strategy;
#[cfg(not(target_arch = "wasm32"))]
pub mod playtest_system;
pub mod proximity_system;
pub mod relationship_directive_system;
pub mod resource_system;
pub mod scenario_system;
pub mod social_system;
pub mod summary_system;
pub mod time_events;
pub mod time_system;
pub mod work_system;
